# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push, pull_request]
#
#  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Racket
      uses: Bogdanp/setup-racket@v0.12
      with:
        architecture: 'x64'
        distribution: 'minimal'
        version: 7.4
        packages: 'compiler-lib'
